import {putMedia,deleteMedia,mediaURL} from './media-store.js';
import {generateWithRetries} from './generator.js';

const STORAGE='shala_state_v2', CREATE='shala_create_me_v2';
const STAGES=['clothing','bag','shoes','accessory'];
const NEXT={clothing:'bag',bag:'shoes',shoes:'accessory',accessory:null};
const defaults={giftOpened:false,createMeCompleted:false,canon:null,favorites:[null,null,null],firstFavoriteTriviaShown:false,pendingReveal:null,screen:'gift',focus:null,pose:null,studio:null,stage:null,currentLabel:null,currentMediaKey:null,references:{},working:false,workingAttempt:0};
let state={...defaults,...load(STORAGE)};
let cm={step:'face',face:null,heightCm:null,weightKg:null,bustCm:null,waistCm:null,hipsCm:null,candidate:null,manualChoice:null,...load(CREATE)};
let mirrorStream=null, activeURLs=[];
const app=document.querySelector('#app');

function load(k){try{return JSON.parse(localStorage.getItem(k)||'{}')}catch{return {}}}
function persist(){localStorage.setItem(STORAGE,JSON.stringify(state));localStorage.setItem(CREATE,JSON.stringify(cm))}
function patch(p){state={...state,...p};persist();render()}
function patchCM(p){cm={...cm,...p};persist();createMe()}
function cleanURLs(){activeURLs.forEach(URL.revokeObjectURL);activeURLs=[]}
function stopMirror(){if(mirrorStream){mirrorStream.getTracks().forEach(t=>t.stop());mirrorStream=null}}
function button(text,cls,fn){const b=document.createElement('button');b.textContent=text;b.className=cls;b.addEventListener('click',fn);return b}
function shell(title){cleanURLs();stopMirror();app.innerHTML='';const s=document.createElement('section');s.className='screen';if(title){const h=document.createElement('div');h.className='stage center';h.textContent=title;s.append(h)}app.append(s);return s}
function field(label,id,value,attrs=''){return `<label class="field"><span>${label}</span><input id="${id}" value="${value??''}" ${attrs}></label>`}
const inch=v=>v/2.54, cmIn=v=>v*2.54, lb=v=>v*2.2046226218, kg=v=>v/2.2046226218;
function ftIn(c){if(!c)return{ft:'',inch:''};const total=inch(c),ft=Math.floor(total/12);return{ft,inch:(total-ft*12).toFixed(1)}}
function bodyShape(b,w,h){if(!b||!w||!h)return'rectangle';const bh=Math.abs(b-h)/Math.max(b,h),drop=Math.min((b-w)/b,(h-w)/h);if(drop>=.22&&bh<=.06)return'hourglass';if(h>b*1.08)return drop>=.18?'bottom-hourglass':'pear';if(b>h*1.08)return drop>=.18?'top-hourglass':'inverted-triangle';if(w>=Math.min(b,h)*.88)return'apple';return'rectangle'}
function resolveCanon(){const h=cm.heightCm,w=cm.weightKg;if(!h||!w)return null;const bmi=w/((h/100)**2),height=h<157?'short':h<170?'medium':'tall',build=bmi<21?'lean':bmi<27?'medium':'full',shape=bodyShape(cm.bustCm,cm.waistCm,cm.hipsCm),hs={short:0,medium:1,tall:2},bs={lean:0,medium:1,full:2},shapes=['hourglass','bottom-hourglass','top-hourglass','pear','inverted-triangle','rectangle','apple'];return{height,build,shape,seed:hs[height]*21+bs[build]*7+shapes.indexOf(shape)+1,bmi:+bmi.toFixed(1)}}

function render(){if(state.pendingReveal&&state.screen!=='reveal')state.screen='reveal';if(!state.giftOpened)return gift();if(!state.createMeCompleted)return createMe();const fn={compact,mirror,workshop,pose,studio,clothing:()=>referenceStage('clothing'),bag:()=>referenceStage('bag'),shoes:()=>referenceStage('shoes'),accessory:()=>referenceStage('accessory'),reveal,favorites,trend}[state.screen]||compact;fn()}

function gift(){const s=shell();const c=document.createElement('div');c.className='compact';c.textContent='SHALA';s.append(c);const n=document.createElement('div');n.className='note';n.innerHTML=`<div class="cake">🎂</div><p>This is for you to use, explore and most especially—enjoy.</p><p>Thank you for literally saving my life. I'll use up all my chances to return your kindness.</p><p>Forever my sistah, forever your brotha'<br><strong>RJ</strong></p>`;s.append(n);s.append(button('♡','btn-go',()=>patch({giftOpened:true,screen:'createMe'})))}
function pane(s,icon,title,copy){const d=document.createElement('div');d.className='create-card';d.innerHTML=`<div class="scene-icon">${icon}</div><h1>${title}</h1><p>${copy}</p>`;s.append(d);return d}
function createMe(){const s=shell('CREATE ME');({face:facePane,height:heightPane,weight:weightPane,measure:measurePane,albus:albusPane,confirm:canonConfirm,really:reallyPane,manual:manualPane,manualPreview}[cm.step]||facePane)(s)}
function facePane(s){const d=pane(s,'📸','FIRST, YOU.','Take or choose a clear front-facing photo.');const i=document.createElement('input');i.type='file';i.accept='image/*';i.capture='user';i.className='file-input';d.append(i);i.onchange=()=>{if(i.files?.[0]){cm.face=i.files[0].name;persist()}};s.append(button(cm.face?'CONTINUE':'USE CAMERA / PHOTO','btn-go',()=>patchCM({face:cm.face||'camera-face',step:'height'})))}
function heightPane(s){const d=pane(s,'📏','HOW TALL ARE WE?','Metric and Imperial stay linked.'),f=ftIn(cm.heightCm);d.insertAdjacentHTML('beforeend',`<div class="unit-grid">${field('CM','hc',cm.heightCm,'inputmode=decimal')}${field('FT','hf',f.ft,'inputmode=numeric')}${field('IN','hi',f.inch,'inputmode=decimal')}</div>`);const c=d.querySelector('#hc'),ft=d.querySelector('#hf'),ii=d.querySelector('#hi');c.oninput=()=>{const v=+c.value;if(v){cm.heightCm=v;const x=ftIn(v);ft.value=x.ft;ii.value=x.inch;persist()}};const imp=()=>{const v=cmIn((+ft.value||0)*12+(+ii.value||0));if(v){cm.heightCm=v;c.value=v.toFixed(1);persist()}};ft.oninput=ii.oninput=imp;s.append(button('NEXT','btn-go',()=>cm.heightCm?patchCM({step:'weight'}):alert('Give SHALA your height, gurl.')))}
function weightPane(s){const d=pane(s,'⚖️','AND ON THE SCALE?','Height and weight resolve relative build together.');d.insertAdjacentHTML('beforeend',`<div class="unit-grid two">${field('KG','wk',cm.weightKg?.toFixed(1)||'','inputmode=decimal')}${field('LB','wl',cm.weightKg?lb(cm.weightKg).toFixed(1):'','inputmode=decimal')}</div>`);const k=d.querySelector('#wk'),l=d.querySelector('#wl');k.oninput=()=>{if(+k.value){cm.weightKg=+k.value;l.value=lb(cm.weightKg).toFixed(1);persist()}};l.oninput=()=>{if(+l.value){cm.weightKg=kg(+l.value);k.value=cm.weightKg.toFixed(1);persist()}};s.append(button('NEXT','btn-go',()=>cm.weightKg?patchCM({step:'measure'}):alert('We need the number on the scale.')))}
function measurePane(s){const d=pane(s,'🧵','THE TAPE, PLEASE.','Bust, waist and hips help ALBUS resolve geometry.');[['BUST','bustCm'],['WAIST','waistCm'],['HIPS','hipsCm']].forEach(([label,key])=>{d.insertAdjacentHTML('beforeend',`<div class="measure-row"><strong>${label}</strong>${field('CM',key,cm[key]?.toFixed(1)||'','inputmode=decimal')}${field('IN',key+'i',cm[key]?inch(cm[key]).toFixed(1):'','inputmode=decimal')}</div>`);const c=d.querySelector(`#${key}`),i=d.querySelector(`#${key}i`);c.oninput=()=>{if(+c.value){cm[key]=+c.value;i.value=inch(cm[key]).toFixed(1);persist()}};i.oninput=()=>{if(+i.value){cm[key]=cmIn(+i.value);c.value=cm[key].toFixed(1);persist()}}});s.append(button('DO THE MATH','btn-go',()=>cm.bustCm&&cm.waistCm&&cm.hipsCm?patchCM({candidate:resolveCanon(),step:'albus'}):alert('Bust, waist and hips first, gurl.')))}
function albusPane(s){pane(s,'🧮','ALBUS IS DOING THE MATH...','One dramatic calculator later.');setTimeout(()=>cm.step==='albus'&&patchCM({candidate:resolveCanon(),step:'confirm'}),850)}
function candidateCard(d,c){d.insertAdjacentHTML('beforeend',`<div class="silhouette"><span>◇</span><small>SEED ${c?.seed||'—'} · ${c?.height||''} · ${c?.build||''}</small></div>`)}
function canonConfirm(s){const d=pane(s,'✨','DOES THIS RESEMBLE YOU?','ALBUS has proposed one Canon candidate. You have final authority.');candidateCard(d,cm.candidate);const a=document.createElement('div');a.className='actions cols2';a.append(button('NO','btn-neutral',()=>patchCM({step:'really'})));a.append(button('YES','btn-go',()=>acceptCanon(cm.candidate)));s.append(a)}
function reallyPane(s){pane(s,'👀','REALLY, GURL?','Math has feelings now.');const a=document.createElement('div');a.className='actions cols2';a.append(button('GO BACK','btn-neutral',()=>patchCM({step:'confirm'})));a.append(button('NA-AH!','btn-go',()=>patchCM({step:'manual'})));s.append(a)}
function manualPane(s){const d=pane(s,'👗','WHICH ONE FEELS LIKE YOU?','Same height/build family. Seven geometries.');const g=document.createElement('div');g.className='body-grid';['pear','top-hourglass','rectangle','hourglass','apple','bottom-hourglass','inverted-triangle'].forEach((shape,i)=>g.append(button(['♢','♢','▯','⌛','◯','♢','▽'][i],'body-choice',()=>patchCM({manualChoice:shape,step:'manualPreview'}))));d.append(g)}
function manualPreview(s){const d=pane(s,'✨','THIS ONE?','Preview before committing your Canon.');candidateCard(d,{...cm.candidate,shape:cm.manualChoice});const a=document.createElement('div');a.className='actions cols2';a.append(button('CHOOSE AGAIN','btn-neutral',()=>patchCM({step:'manual'})));a.append(button('THIS ONE','btn-go',()=>acceptCanon({...cm.candidate,shape:cm.manualChoice,manualOverride:true})));s.append(a)}
function acceptCanon(canon){state={...state,createMeCompleted:true,canon,screen:'compact'};cm.step='complete';persist();render()}

function compact(){const s=shell(),c=document.createElement('div');c.className='compact';c.textContent='SHALA';s.append(c);const p=document.createElement('div');p.className='palette';[['MIRROR ON THE WALL','btn-neutral',()=>patch({screen:'mirror'})],['EXPLORE','pan explore',()=>patch({screen:'workshop'})],['TREND ALERT','pan trend',()=>patch({screen:'trend'})],['FAVORITES','pan faves',()=>patch({screen:'favorites'})]].forEach(x=>p.append(button(...x)));s.append(p)}
async function mirror(){const s=shell('MIRROR ON THE WALL'),v=document.createElement('video');v.className='mirror-video';v.autoplay=true;v.playsInline=true;v.muted=true;s.append(v);const msg=document.createElement('p');msg.className='center muted';msg.textContent='As you are, gurl.';s.append(msg);const a=document.createElement('div');a.className='actions cols2';a.append(button('FLIP','btn-neutral',()=>v.classList.toggle('unflipped')));a.append(button('CLOSE','btn-go',()=>patch({screen:'compact'})));s.append(a);try{mirrorStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user'},audio:false});v.srcObject=mirrorStream}catch{msg.textContent='Camera said no. Check camera permission, gurl.'}}
function workshop(){const s=shell('WHAT ARE WE TRYING ON?'),g=document.createElement('div');g.className='hotspots';['CLOTHES','BAGS','SHOES','ACCESSORIES'].forEach(x=>g.append(button(`${x}\nTRY ME`,'hotspot',()=>patch({focus:x.toLowerCase(),screen:'pose'}))));s.append(g)}
function pose(){const s=shell('POSE'),g=document.createElement('div');g.className='pose-grid';for(let i=1;i<=10;i++)g.append(button(`POSE ${i}`,'pose',()=>patch({pose:i,screen:'studio'})));s.append(g)}
function studio(){const s=shell('STUDIO');['INDOOR OFFICE','INDOOR LIVING ROOM','INDOOR DISCO','OUTDOOR SUNNY PATIO','OUTDOOR GOLDEN HOUR'].forEach(x=>s.append(button(x,'btn-neutral',()=>patch({studio:x,stage:'clothing',screen:'clothing',currentLabel:`CANON ${state.canon?.seed||'—'} · POSE ${state.pose} · ${x}`}))))}

async function heroFor(s){const h=document.createElement('div');h.className='hero';if(state.currentMediaKey){const url=await mediaURL(state.currentMediaKey);if(url){activeURLs.push(url);const img=document.createElement('img');img.src=url;img.alt='Last successful SHALA look';h.append(img)}}if(!h.childNodes.length)h.innerHTML=`<div class="center"><h2>${state.currentLabel||'YOUR CANON'}</h2><p>Last successful Look stays here.</p></div>`;s.append(h);return h}
async function previewReference(s,ref){const url=await mediaURL(ref.mediaKey);if(!url)return;activeURLs.push(url);const box=document.createElement('div');box.className='reference-preview';box.innerHTML=`<img src="${url}" alt="Selected reference"><p>${ref.name}</p>`;s.append(box)}
async function acquire(stage,file){const key=`reference:${stage}:${Date.now()}`;await putMedia(key,file);state.references={...state.references,[stage]:{mediaKey:key,name:file.name,status:'preview'}};persist();render()}
async function retake(stage){const old=state.references?.[stage];if(old?.mediaKey)await deleteMedia(old.mediaKey);const refs={...state.references};delete refs[stage];patch({references:refs})}
function acceptReference(stage){const refs={...state.references,[stage]:{...state.references[stage],status:'accepted'}};patch({references:refs})}
async function referenceStage(stage){const s=shell(stage.toUpperCase());await heroFor(s);const ref=state.references?.[stage];if(!ref){const card=document.createElement('div');card.className='reference-card';card.innerHTML=`<h2>${stage==='clothing'?'CLOTHING':stage.toUpperCase()}</h2><p>Show SHALA the reference.</p>`;const input=document.createElement('input');input.type='file';input.accept='image/*';input.capture='environment';input.className='file-input';input.onchange=()=>input.files?.[0]&&acquire(stage,input.files[0]);card.append(input);s.append(card);s.append(button('SKIP >>>','btn-neutral',()=>skipStage(stage)));return}
await previewReference(s,ref);
if(ref.status==='preview'){const a=document.createElement('div');a.className='actions cols2';a.append(button('RETAKE','btn-neutral',()=>retake(stage)));a.append(button('ACCEPT','btn-go',()=>acceptReference(stage)));s.append(a);return}
const a=document.createElement('div');a.className='actions';a.append(button('CHANGE','btn-neutral',()=>retake(stage)));const slap=button(state.working?`WERKING ${state.workingAttempt||''}...`:'SLAP IT','btn-go',()=>generateStage(stage));slap.disabled=state.working;a.append(slap);a.append(button('SKIP >>>','btn-neutral',()=>!state.working&&skipStage(stage)));a.append(button('START AGAIN','btn-peached',startAgain));s.append(a)}
function skipStage(stage){const next=NEXT[stage];if(next)patch({stage:next,screen:next});else commitReveal(state.currentMediaKey,state.currentLabel||'CANON LOOK')}
async function generateStage(stage){if(state.working)return;const ref=state.references?.[stage];if(!ref||ref.status!=='accepted')return;state.working=true;state.workingAttempt=1;persist();render();try{const result=await generateWithRetries({stage,baseLabel:state.currentLabel||`CANON ${state.canon?.seed||'—'}`,referenceName:ref.name},{maxAttempts:3,onAttempt:a=>{state.workingAttempt=a;persist()}});const key=`generated:${Date.now()}`;await putMedia(key,result.blob);state.currentMediaKey=key;state.currentLabel=result.label;state.working=false;state.workingAttempt=0;const next=NEXT[stage];if(next){state.stage=next;state.screen=next;persist();render()}else commitReveal(key,result.label)}catch{state.working=false;state.workingAttempt=0;persist();generationFailure(stage)}}
function generationFailure(stage){const s=shell('REALLY, GURL?');const p=document.createElement('p');p.className='center';p.textContent='The Look did not advance. Your last successful image is untouched.';s.append(p);const a=document.createElement('div');a.className='actions cols2';a.append(button('SWAP','btn-neutral',()=>retake(stage)));a.append(button('START AGAIN','btn-peached',startAgain));s.append(a)}
function startAgain(){if(confirm('Start this look again?'))patch({focus:null,pose:null,studio:null,stage:null,currentLabel:null,currentMediaKey:null,pendingReveal:null,references:{},working:false,workingAttempt:0,screen:'workshop'})}
function commitReveal(mediaKey,label){state.pendingReveal={mediaKey,label,createdAt:Date.now()};state.screen='reveal';persist();render()}

async function reveal(){const s=shell(),h=document.createElement('div');h.className='hero reveal-hero';const key=state.pendingReveal?.mediaKey;if(key){const url=await mediaURL(key);if(url){activeURLs.push(url);const img=document.createElement('img');img.src=url;img.alt='Completed SHALA look';h.append(img)}}if(!h.childNodes.length)h.innerHTML=`<div class="center"><h1>WERK!</h1><p>${state.pendingReveal?.label||state.currentLabel||'FINAL LOOK'}</p></div>`;s.append(h);const c=document.createElement('div');c.className='reveal-controls hidden';c.append(button('♡ MARK FAVORITE','btn-neutral',favoriteCurrent));c.append(button('↓ SAVE TO DEVICE','btn-neutral',saveReveal));c.append(button('TRY NEW ONE','btn-go',()=>patch({pendingReveal:null,focus:null,pose:null,studio:null,stage:null,currentLabel:null,currentMediaKey:null,references:{},screen:'workshop'})));s.append(c);let shown=false;const show=()=>{shown=true;c.classList.remove('hidden')};const timer=setTimeout(show,10000);h.ondblclick=()=>{clearTimeout(timer);show()};h.onclick=()=>shown&&c.classList.toggle('hidden')}
async function saveReveal(){const key=state.pendingReveal?.mediaKey;if(!key)return alert('Only saving can save you in this economy.');const url=await mediaURL(key);if(!url)return;const a=document.createElement('a');a.href=url;a.download=`SHALA-${Date.now()}.svg`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function favoriteCurrent(){const item={mediaKey:state.pendingReveal?.mediaKey,label:state.pendingReveal?.label,createdAt:Date.now()},f=[...state.favorites],slot=[1,0,2].find(i=>!f[i]);if(slot===undefined)return alert("Three's a crowd, gurl. Pick one to let go.");f[slot]=item;const trivia=!state.firstFavoriteTriviaShown;state={...state,favorites:f,firstFavoriteTriviaShown:true};persist();if(trivia)alert('DID YOU KNOW?\n\nWe rendered 63 versions of you,\nand that’s how much we love YOU.');render()}
function favorites(){const s=shell('FAVORITE THINGS'),g=document.createElement('div');g.className='pose-grid';state.favorites.forEach(x=>g.append(button(x?.label||'EMPTY FRAME','pose',()=>{})));s.append(g);s.append(button('HOME','btn-go',()=>patch({screen:'compact'})))}
function trend(){const s=shell('TREND ALERT'),lanes=['lounge clothes','street style','casual',"Sunday's best"],lane=lanes[Math.floor(Math.random()*4)],now=new Date(),q=`women's ${lane} ${now.toLocaleString(undefined,{month:'long'})} ${now.getFullYear()} fashion magazine`;const d=document.createElement('div');d.className='note';d.innerHTML=`<h2>${lane.toUpperCase()}</h2>`;s.append(d);s.append(button('SHOW ME','btn-go',()=>window.open(`https://www.google.com/search?tbm=isch&q=${encodeURIComponent(q)}`,'_blank')));s.append(button('PULL AGAIN','btn-neutral',trend));s.append(button('HOME','btn-neutral',()=>patch({screen:'compact'})))}

render();
